# Generated by Django 3.2.12 on 2022-03-04 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='送信者'),
        ),
    ]
